spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/myDB;AUTO_SERVER=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: QuizzizBackend
server:
  port: 8080
app:
  name: QuizzizBackend