spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizziz_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: QuizzizBackend
server:
  port: 8080
app:
  name: QuizzizBackend